#properties for the local environment
 
api:
  id: "123456" 
   
#Http Listener Configuration
http:
  port: "8081" 
  request:
    protocol: "HTTP"
    host: "healthcare-sys-api"
    port: ""
    path: "/api/eligibility-inquiry" 